version: '3'
services:
  bot:
    container_name: telegram-bot-for-u2
    image: telegram-bot-for-u2
    build: .
    restart: always
    environment:
      - BOT_TOKEN=your_bot_token
      - BOT_NAME=your_bot_name
#      - PROXY_HOST=your_proxy_host
#      - PROXY_PORT=your_proxy_port
#      - PROXY_TYPE=SOCKS4 | SOCKS5 | HTTP
    volumes:
      - ./data:/Telegram-Bot-For-U2/