spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./u2-bot.db
    username:
    password:

mybatis:
  mapper-locations: mapper/*Mapper.xml

bot:
  token: ${BOT_TOKEN:}
  username: ${BOT_NAME:}
  proxy:
    host: ${PROXY_HOST:localhost}
    port: ${PROXY_PORT:1080}
    type: ${PROXY_TYPE:NO_PROXY} #SOCKS4 | SOCKS5 | HTTP

u2:
  cookie:

user:
  id:

phantomjs:
  path:

#logging:
#  level:
#    root: debug
