spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./u2-bot.db
    username:
    password:

mybatis:
  mapper-locations: mapper/*Mapper.xml

user:
  id:

bot:
  api:
  token:
  username:

u2:
  domain: https://u2.dmhy.org
  cookie:

phantomjs:


#logging:
#  level:
#    root: debug
